In [159]:
import numpy as np

In [160]:
np.__version__

'1.20.1'

In [161]:
x = np.array([1,2,3,4,5,6])

In [162]:
type(x)

numpy.ndarray

In [163]:
id(x)

140102266303376

In [164]:
y = np.array(['Rafay', 5,6,7,'Hello'])

In [165]:
print(y)

['Rafay' '5' '6' '7' 'Hello']


In [166]:
y

array(['Rafay', '5', '6', '7', 'Hello'], dtype='<U21')

In [167]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
x = np.arange(10,20,3)

In [169]:
print(x)

[10 13 16 19]


In [170]:
m = np.linspace(10,100,5)

In [171]:
print(m)

[ 10.   32.5  55.   77.5 100. ]


In [172]:
y=np.zeros(20)

In [173]:
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [174]:
m= np.array(([1,2,3],[4,5,6]))

In [175]:
print(m)

[[1 2 3]
 [4 5 6]]


In [176]:
y[-1]

0.0

# Indexing and Silicing

In [177]:
a =[1,2,3,4,5,6,10]
a[:2]
a[-1]

10

In [178]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [179]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [180]:
a[2][1]

8

In [181]:
a[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [182]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [183]:
a[:1]

array([[1, 2, 3]])

In [184]:
a[2: , :1]

array([[7]])

Facing Indexing

In [185]:
arr = np.arange(100)

In [186]:
arrMask = ((arr%5==0))

In [187]:
print(arrMask)

[ True False False False False  True False False False False  True False
 False False False  True False False False False  True False False False
 False  True False False False False  True False False False False  True
 False False False False  True False False False False  True False False
 False False  True False False False False  True False False False False
  True False False False False  True False False False False  True False
 False False False  True False False False False  True False False False
 False  True False False False False  True False False False False  True
 False False False False]


In [188]:
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [189]:
arr = np.arange(100)

In [190]:
arrMas = (((arr%2) == 0) & (arr>50)  & (arr<80))

In [191]:
arr[arrMas]

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78])

In [192]:
arr.shape

(100,)

In [193]:
arr.size

100

In [194]:
arr.transpose

<function ndarray.transpose>

In [195]:
arr.ndim

1

In [196]:
arrr= np.array([1,2,3,4,5,6])
b = arrr.T
b

array([1, 2, 3, 4, 5, 6])

In [197]:
arr= np.arange(15)
r=arr.reshape(3,5)
print(r)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# Append

In [198]:
a = np.array([[1,2],[3,4]])
b= np.append(a,[[9,9]], axis=0)

In [199]:
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [200]:
a = np.array([[1,2],[3,4]])
b= np.append(a,[[9],[9]], axis=1).copy()

In [201]:
b

array([[1, 2, 9],
       [3, 4, 9]])

# Removing

In [202]:
d = np.delete(b,0,axis=0)
print(d)

[[3 4 9]]


In [203]:
print(d)

[[3 4 9]]


# Pratice Question

In [204]:
import numpy as np

In [205]:
# creating an array
arr= np.linspace(1,50,25)

In [206]:
# printing an array
print(arr)
print(len(arr))

[ 1.          3.04166667  5.08333333  7.125       9.16666667 11.20833333
 13.25       15.29166667 17.33333333 19.375      21.41666667 23.45833333
 25.5        27.54166667 29.58333333 31.625      33.66666667 35.70833333
 37.75       39.79166667 41.83333333 43.875      45.91666667 47.95833333
 50.        ]
25


In [207]:
# displaying the type of the array
type(arr)

numpy.ndarray

In [208]:
# display the shape
arr.shape

(25,)

In [209]:
display_value = ((arr>20))

In [210]:
c =arr[display_value].copy()


In [211]:
print(c)

[21.41666667 23.45833333 25.5        27.54166667 29.58333333 31.625
 33.66666667 35.70833333 37.75       39.79166667 41.83333333 43.875
 45.91666667 47.95833333 50.        ]


In [212]:
r = arr.reshape(5,5)

In [213]:
print(r)

[[ 1.          3.04166667  5.08333333  7.125       9.16666667]
 [11.20833333 13.25       15.29166667 17.33333333 19.375     ]
 [21.41666667 23.45833333 25.5        27.54166667 29.58333333]
 [31.625      33.66666667 35.70833333 37.75       39.79166667]
 [41.83333333 43.875      45.91666667 47.95833333 50.        ]]


In [214]:
# only delete is left from this program

# Session 02

In [215]:
x = np.arange(50)

In [216]:
## this is th power of element and in the below example the powser is 3 
x**3

array([     0,      1,      8,     27,     64,    125,    216,    343,
          512,    729,   1000,   1331,   1728,   2197,   2744,   3375,
         4096,   4913,   5832,   6859,   8000,   9261,  10648,  12167,
        13824,  15625,  17576,  19683,  21952,  24389,  27000,  29791,
        32768,  35937,  39304,  42875,  46656,  50653,  54872,  59319,
        64000,  68921,  74088,  79507,  85184,  91125,  97336, 103823,
       110592, 117649])

In [217]:
x.round()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [218]:
# this will show the max values in the matrix
x.max()

49

In [219]:
# this will display a mean of the matrix
x.mean()

24.5

### 50 and 80 equal 20
### underroor
### sum
### mean
### vairiance
### standard diviation

In [220]:
arr= np.linspace(50,80,20)

In [221]:
print(arr)

[50.         51.57894737 53.15789474 54.73684211 56.31578947 57.89473684
 59.47368421 61.05263158 62.63157895 64.21052632 65.78947368 67.36842105
 68.94736842 70.52631579 72.10526316 73.68421053 75.26315789 76.84210526
 78.42105263 80.        ]


In [222]:
arr=arr.round()

In [223]:
# sum
sum1=arr.sum().copy()

In [224]:
print(sum1)

1300.0


In [225]:
# mean
mean= arr.mean().copy()

In [226]:
print(mean)

65.0


In [227]:
# variance
variance =arr.var().copy() 

In [228]:
print(variance)

82.5


In [229]:
# under root
under_root = arr.std().copy()

In [230]:
print(under_root)

9.082951062292475


In [231]:
# unique functin wills how only the unique value but it is a numpy function 
arr = np.array([1,1,2,3,3,5,6,6,7])
np.unique(arr)

array([1, 2, 3, 5, 6, 7])

In [232]:
arr.sort()

In [233]:
# this is a numpy function and it will sort first and then find the mid point from the array
np.median(arr)

3.0

In [234]:
x = np.arange(1,10)

In [235]:
x = x.reshape(3,-1)

In [236]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [237]:
# zero represent x axis
# one represent y axis
print(x.mean(axis=0))

[4. 5. 6.]


In [238]:
np.random.seed(123)

In [239]:
x= np.random.randint(10, size =1000 )

In [240]:
print(x)

[2 2 6 1 3 9 6 1 0 1 9 0 0 9 3 4 0 0 4 1 7 3 2 4 7 2 4 8 0 7 9 3 4 6 1 5 6
 2 1 8 3 5 0 2 6 2 4 4 6 3 0 6 4 7 6 7 1 5 7 9 2 4 8 1 2 1 1 3 5 9 0 8 1 6
 3 3 5 9 7 9 2 3 3 3 8 6 9 7 6 3 9 6 6 6 1 3 4 3 1 0 5 8 6 8 9 1 0 3 1 3 4
 7 6 1 4 3 3 7 6 8 6 4 4 7 0 0 9 8 8 4 8 6 1 6 8 7 9 1 7 1 7 9 8 7 1 3 1 8
 7 5 1 2 5 2 2 9 3 2 6 7 9 1 3 8 3 7 9 9 3 3 5 6 0 8 7 7 4 4 5 0 8 9 2 5 1
 5 9 2 4 3 0 3 7 7 2 5 1 7 5 9 1 2 8 5 0 9 3 3 3 1 7 6 3 1 7 2 6 5 9 8 9 4
 7 8 5 9 2 4 3 3 1 7 8 5 7 7 7 5 0 0 8 1 0 4 5 4 5 0 7 1 2 2 7 7 3 6 1 8 4
 1 6 5 9 0 3 1 3 7 7 7 5 3 6 3 5 1 5 9 1 3 9 1 5 6 1 5 0 7 0 3 0 6 2 7 5 1
 0 0 2 6 5 9 1 5 3 6 4 7 1 6 0 3 1 3 0 8 5 1 4 3 2 2 0 2 0 2 7 9 0 3 9 7 0
 5 4 6 0 7 8 8 1 0 1 7 5 3 0 4 8 4 9 3 5 1 8 0 9 1 5 8 8 4 6 8 7 9 2 0 0 9
 9 5 3 5 5 2 2 7 3 1 3 9 3 6 2 3 1 9 8 0 2 3 7 9 2 7 9 7 1 4 7 4 7 8 0 2 7
 4 3 7 3 7 0 7 6 8 6 8 0 5 3 2 4 3 3 9 7 1 8 0 1 4 7 2 4 8 3 4 9 6 2 7 7 7
 4 7 8 4 0 7 6 3 4 1 1 7 2 7 8 9 4 4 4 7 7 9 9 4 1 5 5 8 9 5 1 0 6 0 9 4 6
 4 5 3 4 6 2 5 2 4 3 2 4 

In [241]:
quiz= np.random.randint(0,15, size =15 )

In [242]:
print(quiz)

[ 2  1  6  5  3 11  1  5  8  8  5 13 13  5 14]


In [243]:
assignment= np.random.randint(0,15, size= 50)

In [244]:
print(assignment)

[ 4  9  3 12 10  3  4  1 13 10  9  5  9 11 13  7 13  8  2 11  8  1  6 10
  0 11  2  4  5  8 12 11  4  5  0 11  3  7 14 12  2 10  5  0  0  2  2  2
  7  8]


In [245]:
quiz.max()

14

In [246]:
assignment.max()

14

In [247]:
max_quiz= (quiz > 10)

In [248]:
quiz[max_quiz]

array([11, 13, 13, 14])

In [249]:
max_assignment = (assignment < 30)

In [250]:
student_max_assignment=assignment[max_assignment].copy()

In [251]:
print(student_max_assignment)

[ 4  9  3 12 10  3  4  1 13 10  9  5  9 11 13  7 13  8  2 11  8  1  6 10
  0 11  2  4  5  8 12 11  4  5  0 11  3  7 14 12  2 10  5  0  0  2  2  2
  7  8]


In [255]:
import numpy as np
A = np.array([[3,5,9],[8,1,6],[2,7,4]])

In [256]:
print(A)

[[3 5 9]
 [8 1 6]
 [2 7 4]]


In [260]:
B = np.array([[35],[29],[1]])

In [261]:
print(B)

[[35]
 [29]
 [ 1]]


In [262]:
inverse_A=np.linalg.inv(A).copy()

In [265]:
print(inverse_A)

[[-0.13970588  0.15808824  0.07720588]
 [-0.07352941 -0.02205882  0.19852941]
 [ 0.19852941 -0.04044118 -0.13602941]]


In [267]:
ans= np.dot(inverse_A,B)

In [268]:
print(ans)

[[-0.22794118]
 [-3.01470588]
 [ 5.63970588]]
