In [11]:
import numpy as np

In [12]:
np.__version__

'1.20.1'

In [13]:
x = np.array([1,2,3,4,5,6])

In [14]:
type(x)

numpy.ndarray

In [15]:
id(x)

140537639921872

In [16]:
y = np.array(['Rafay', 5,6,7,'Hello'])

In [17]:
print(y)

['Rafay' '5' '6' '7' 'Hello']


In [20]:
y

array(['Rafay', '5', '6', '7', 'Hello'], dtype='<U21')

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x = np.arange(10,20,3)

In [25]:
print(x)

[10 13 16 19]


In [30]:
m = np.linspace(10,100,5)

In [31]:
print(m)

[ 10.   32.5  55.   77.5 100. ]


In [33]:
y=np.zeros(20)

In [34]:
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
m= np.array(([1,2,3],[4,5,6]))

In [38]:
print(m)

[[1 2 3]
 [4 5 6]]


In [40]:
y[-1]

0.0

# Indexing and Silicing

In [43]:
a =[1,2,3,4,5,6,10]
a[:2]
a[-1]

10

In [44]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [45]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
a[2][1]

8

In [47]:
a[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [48]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [49]:
a[:1]

array([[1, 2, 3]])

In [51]:
a[2: , :1]

array([[7]])

Facing Indexing

In [53]:
arr = np.arange(100)

In [54]:
arrMask = ((arr%5==0))

In [55]:
print(arrMask)

[ True False False False False  True False False False False  True False
 False False False  True False False False False  True False False False
 False  True False False False False  True False False False False  True
 False False False False  True False False False False  True False False
 False False  True False False False False  True False False False False
  True False False False False  True False False False False  True False
 False False False  True False False False False  True False False False
 False  True False False False False  True False False False False  True
 False False False False]


In [56]:
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [57]:
arr = np.arange(100)

In [58]:
arrMas = (((arr%2) == 0) & (arr>50)  & (arr<80))

In [59]:
arr[arrMas]

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78])

In [60]:
arr.shape

(100,)

In [61]:
arr.size

100

In [62]:
arr.transpose

<function ndarray.transpose>

In [64]:
arr.ndim

1

In [71]:
arrr= np.array([1,2,3,4,5,6])
b = arrr.T
b

array([1, 2, 3, 4, 5, 6])

In [80]:
arr= np.arange(15)
r=arr.reshape(3,5)
print(r)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# Append

In [85]:
a = np.array([[1,2],[3,4]])
b= np.append(a,[[9,9]], axis=0)

In [86]:
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [99]:
a = np.array([[1,2],[3,4]])
b= np.append(a,[[9],[9]], axis=1).copy()

In [100]:
b

array([[1, 2, 9],
       [3, 4, 9]])

# Removing

In [106]:
d = np.delete(b,0,axis=0)
print(d)

[[3 4 9]]


In [104]:
print(d)

NameError: name 'd' is not defined